# Generated by Django 4.2.29 on 2026-03-20 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🌿", max_length=50)),
            ],
            options={
                "verbose_name_plural": "Waste Categories",
            },
        ),
        migrations.CreateModel(
            name="WasteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilograms"),
                            ("ton", "Tonnes"),
                            ("liter", "Litres"),
                            ("bundle", "Bundles"),
                        ],
                        default="kg",
                        max_length=10,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "possible_products",
                    models.TextField(help_text="e.g. Compost, Biofertilizer, Biogas"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="waste_items/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("pending", "Pending"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.wastecategory",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
